version: '3'
services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root

    php:
        build: ./php7-fpm
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/
        links:
          - db:mysqldb
          - rabbit:rabbit

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
            - rabbit
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        depends_on:
            - php
            - nginx
    rabbit:
       image: "rabbitmq:3.7-management"
       hostname: "localhost"
       environment:
            - RABBITMQ_ERLANG_COOKIE=12345678
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
            - RABBITMQ_DEFAULT_VHOST=/
       ports:
            - "15672:15672"
            - "5672:5672"
